[package]
name = "db-sqlx-postgres"
version = "0.1.0"
edition = "2021"
homepage = "https://mcaptcha.org"
repository = "https://github.com/mCaptcha/mCaptcha"
documentation = "https://mcaptcha.org/docs/"
license = "AGPLv3 or later version"
authors = ["realaravinth <realaravinth@batsense.net>"]

[dependencies]
async-trait = "0.1.51"
db-core = {path = "../db-core"}
futures = "0.3.15"
sqlx = { version = "0.7", features = [ "runtime-tokio-rustls", "postgres", "time" ] }
uuid = { version = "1.4.0", features = ["v4", "serde"] }

[dev-dependencies]
actix-rt = "2"
sqlx = { version = "0.7", features = [ "runtime-tokio-rustls", "postgres", "time"] }
db-core = {path = "../db-core", features = ["test"]}
url = { version  = "2.2.2", features = ["serde"] }

[package.metadata]
[package.metadata.sqlx]
offline = true